title: "Beautiful Jekyll"
author: "Dean Attali"
email: your-email@example.com
description: >-
  This website is powered by GitHub Pages/Jekyll and can be built for free in under 5 minutes. Literally.
baseurl: ""
url: "https://yourusername.github.io" # Ganti dengan GitHub username kamu

social-network-links:
  github: yourusername
  facebook: yourprofile
  email: your-email@example.com
  youtube: yourchannel
  x: yourusername
  rss: true

theme: beautiful-jekyll-theme
google_analytics: ""
site_logo: /assets/img/avatar-icon.png
favicon: /assets/img/favicon.ico

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_footer: true
footer-links-active:
  github: true
  facebook: true
  email: true
  x: true
  youtube: true
