title: Cut Yumna Assyifa
author: Cut Yumna
description: Portofolio Remedial
baseurl: "" 
url: "https://cutyumnaassyifa22.github.io"
theme: jekyll-theme-cayman

# Optional
social:
  github: cutyumnaassyifa22
  instagram: cutyumna_sy
