title: "Cut Yumna Assyifa"
author: "Cut Yumna Assyifa"
email: "yumna@example.com"
description: >-
  Website portofolio remedial berdasarkan template Beautiful Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cutyumnaassyifa22.github.io"
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed