title: Beautiful Jekyll
author: Yumna Assyifa
description: Personal website of Yumna
url: "https://cutyumnaassyifa22github.io"
baseurl: ""

enable-darkmode: true
permalink: /:title/

navbar-links:
  Beranda: ""
  Tentang Saya: "about"

# ✅ Aktifkan social icon di footer
footer-links-active:
  rss: true
  email: true
  facebook: true
  github: true
  twitter: true
  youtube: true

email: cutyumna139@gmail.com

social-network-links:
  github: cutyumnaassyifa22
  email: cutyumna139@gmail.com
  facebook: cut yumna
  twitter: cut yumna
  youtube: cutyumna
