<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Beautiful Jekyll</title>
  <style>
    body {
      background-color: #1e1e1e;
      font-family: Arial, sans-serif;
      color: white;
      padding: 2rem;
    }
    .card {
      background-color: #2c2c2c;
      border-radius: 10px;
      padding: 1.5rem;
      max-width: 400px;
      margin: auto;
    }
    h2 {
      color: #00cc66;
      margin-bottom: 1rem;
    }
    b {
      color: white;
    }
    .links a {
      color: #00cc66;
      text-decoration: none;
      margin-right: 10px;
    }
  </style>
</head>
<body>
  <div class="card">
    <h2>Tentang Saya</h2>
    <p><b>Nama:</b> Yumna Assyifa</p>
    <p><b>Umur:</b> 18 tahun</p>
    <p><b>Status:</b> Mahasiswi</p>
    <p><b>Kampus:</b> Politeknik Negeri Lhokseumawe</p>
    <p><b>Minat:</b> Web Development, GitHub Pages, dan Jekyll</p>
    <div class="links">
      <a href="https://github.com/cutyumnaassyifa22">GitHub</a> •
      <a href="mailto:cutyumna139@gmail.com">Email</a>
    </div>
  </div>
</body>
</html>
