title: Beautiful Jekyll
author: Yumna Assyifa
description: Personal website of Yumna
url: "https://cutyumnaassyifa22.github.io"
baseurl: ""
enable-darkmode: true
permalink: /:title/

navbar-links:
  Home: ""
  About Me: "about"

footer-links-active:
  github: true
  email: true
  rss: true

email: cutyumna139@gmail.com

social-network-links:
  github: cutyumnaassyifa22
  email: cutyumna139@gmail.com

collections:
  posts:
    output: true
