title: beautifuljekyll
author: Dean Attali
description: >- 
  This is a demo post to show you how to write blog posts with markdown.
baseurl: "" 
url: "https://yifa22.github.io"

markdown: kramdown
theme: beautiful-jekyll

plugins:
  - jekyll-feed

paginate: 5
paginate_path: "/page:num"

# Tag display
tagline: ""
